{
  # Training cofiguration
  'dataset': ecg,
  'img_size': 187,
  'batch_size': 64,
  'inner_steps': 10,
  'inner_steps_boot': 0,
  'data_ratio': 1.0,
  'sample_type': random,
  'lam': 0.0,
  'w0': 10.,
  'w0_increment': 10.,

  # Test configuration
  'test_batch_size': 64,
  'num_test_signals': 256,
  'inner_steps_test': 20,

  # Model config
  'hidden_size': 64,
  'num_layers': 8,
  'latent_modulation_dim': 64,

  # Path to trained model
  'load_path': /path/to/best.model or /path/to/stepXXXX.model,
}