name: medfuncta
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - numpy=2.1.3
  - matplotlib=3.10.1
  - pip:
      - tensorboard
      - pandas
      - nibabel
      - einops
      - medmnist
      - dicom2nifti
      - pytorch_msssim
      - lpips
      - torchmetrics